Lots of improvement
Interated most patches from lapinlampi
Improvement of readability and consistency
Status now output the id/key, type of algo, type of hash and digest of the keys

diff --git a/dnssec-reverb b/dnssec-reverb
--- a/dnssec-reverb
+++ b/dnssec-reverb
@@ -3,25 +3,28 @@
 #
 # @home: https://github.com/northox/dnssec-reverb
 # @license: Simplified BSD
+# Copyright (c) 2017-2020 Danny Fullerton <danny@mantor.org>. 
 # Copyright (c) 2018 Juuso "Linda" Lapinlampi <linda@lindalap.fi>. 
-# Copyright (c) 2017 Danny Fullerton <danny@mantor.org>. 
 # Copyright (c) 2009-2013 Kazunori Fujiwara <fujiwara@wide.ad.jp>.
 
 PROG=$(basename "$0")
 DIR=$(dirname "$0")
-keygen="$(which ldns-keygen)"
-signzone="$(which ldns-signzone)"
-key2ds="$(which ldns-key2ds)"
-checkzone="$(which nsd-checkzone)"
-control="$(which nsd-control)"
-RELOAD_COMMAND="$checkzone \$ZONE \$ZONE || exit 1; $control reload && $control notify"
+KEYGEN_CMD="$(which ldns-keygen)"
+SIGNZONE_CMD="$(which ldns-signzone)"
+KEY2DS_CMD="$(which ldns-key2ds)"
+CHECKZONE_CMD="$(which nsd-checkzone)"
+CONTROL_CMD="$(which nsd-control)"
+RELOAD_CMD="(echo -n 'reload is '; $CONTROL_CMD reload) && (echo -n 'notify is '; $CONTROL_CMD notify)"
 KSK_PARAM="-a ECDSAP256SHA256 -k"
-ZSK_PARAM="-a ECDSAP256SHA256 "
-SIGN_PARAM="-n"
-DS_PARAM="-n -2"
+ZSK_PARAM="-a ECDSAP256SHA256"
+SIGN_PARAM="-n" # -n = use NSEC3
+DS_HASH="2" # 1=SHA1 2=SHA256 3=GOST 4=SHA384
+DS_PARAM="-$DS_HASH"
 SERIAL_TAG="_SERIAL_"
 
 NOW=$(date +%Y%m%d%H%M%S)
+UTIME=$(date +%s)
+EXPIRE=$(echo "$UTIME + (31*24*60*60)" | bc)
 LOCKF=""
 
 Fatal()
@@ -30,6 +33,11 @@ Fatal()
 	echo "$PROG: $1" >&2
 	exit 1
 }
+
+if [ $(id -u) != 0 ]; then
+	Fatal "Must be root"
+fi
+
 
 # load conf
 CONF="dnssec-reverb.conf"
@@ -47,11 +55,11 @@ fi
 . "$CONF"
 
 # defaults
-[ "$keygen" = "" ] && Fatal "Can't find \$keygen"
-[ "$signzone" = "" ] && Fatal "Can't find \$signzone"
-[ "$key2ds" = "" ] && Fatal "Can't find \$key2ds"
-[ "$checkzone" = "" ] && Fatal "Can't find \$checkzone"
-[ "$control" = "" ] && Fatal "Can't find \$control"
+[ "$KEYGEN_CMD" = "" ] && Fatal "Can't find \$KEYZONE_CMD"
+[ "$SIGNZONE_CMD" = "" ] && Fatal "Can't find \$SIGNZONE_CMD"
+[ "$KEY2DS_CMD" = "" ] && Fatal "Can't find \$KEY2DS_CMD"
+[ "$CHECKZONE_CMD" = "" ] && Fatal "Can't find \$CHECKZONE_CMD"
+[ "$CONTROL_CMD" = "" ] && Fatal "Can't find \$CONTROL_CMD"
 [ "$MASTERDIR" = "" ] && Fatal "\$MASTERDIR not set"
 [ -d "$MASTERDIR" ] || Fatal "\$MASTERDIR not a directory ($MASTERDIR)"
 [ "$DBDIR" = "" ] && DBDIR="$MASTERDIR/dnssec-reverb-db"
@@ -59,11 +67,11 @@ fi
 [ "$KEYBACKUPDIR" = "" ] && KEYBACKUPDIR="$DBDIR/backup"
 [ "$SERIALDIR" = "" ] && SERIALDIR="$DBDIR/serial"
 [ "$DSDIR" = "" ] && DSDIR="$DBDIR/ds"
-HEAD_ZSKNAME="zsk-"
-HEAD_KSKNAME="ksk-"
-HEAD_ZSSNAME="zss-"
-HEAD_ZSRNAME="zsr-" # Removed ZSK
-HEAD_KSSNAME="kss-"
+ZSK_CUR_PREFIX="zsk-" # current zsk
+KSK_CUR_PREFIX="ksk-" # current ksk
+ZSK_NEW_PREFIX="zss-" # new zsk
+KSK_NEW_PREFIX="kss-" # new ksk
+ZSK_OLD_PREFIX="zsr-" # removed zsk
 
 # setup
 [ ! -d "$DBDIR" ] && mkdir -p "$DBDIR"
@@ -109,19 +117,18 @@ EOF
 
 sign()
 {
-	_check_file "$ZONEFILE" "$KSK_FILE" "$ZSK_FILE"
-	KSK=$(head -1 "$KSK_FILE")
-	ZSK=$(head -1 "$ZSK_FILE")
+	_check_file "$ZONEFILE" "$KSK_CUR_FILE" "$ZSK_CUR_FILE"
+	KSK=$(head -1 "$KSK_CUR_FILE")
+	ZSK=$(head -1 "$ZSK_CUR_FILE")
 	KSS=""
-	[ -s "$KSK_S_FILE" ] && KSS=$(head -1 "$KSK_S_FILE")
+	[ -s "$KSK_NEW_FILE" ] && KSS=$(head -1 "$KSK_NEW_FILE")
 	_check_file "$KEYDIR/$KSK.private" "$KEYDIR/$ZSK.private"
-
 	LASTSERIAL=0
 	[ -f "$SERIAL_FILE" ] && LASTSERIAL=$(cat "$SERIAL_FILE")
 	LASTDATE=$(echo "$LASTSERIAL" | sed 's/..$//')
 	DATE=$(date +%Y%m%d)
 	if [ "$LASTDATE" = "$DATE" ]; then
-		SERIAL=$(( "$LASTSERIAL" + 1 ))
+		SERIAL=$(( $LASTSERIAL + 1 ))
 		echo "$SERIAL" > "$SERIAL_FILE"
  	else
 		SERIAL=$(date +%Y%m%d00)
@@ -131,12 +138,12 @@ sign()
 	ZONE_PREPROCESS="sed s/$SERIAL_TAG/$SERIAL/"
 	$ZONE_PREPROCESS "$ZONEFILE" > "$ZONEFILE.tmp"
 
-	cat "$KSK_FILE" "$ZSK_FILE" | while read -r keyfile
+	cat "$KSK_CUR_FILE" "$ZSK_CUR_FILE" | while read -r keyfile
 	do
 		_check_file "$KEYDIR/$keyfile.key"
 		cat "$KEYDIR/$keyfile.key" >> "$ZONEFILE.tmp"
 	done
-	for i in $KSK_S_FILE $ZSK_S_FILE $ZSK_R_FILE
+	for i in $KSK_NEW_FILE $ZSK_NEW_FILE $ZSK_OLD_FILE
 	do
 		if [ -s "$i" ]; then
 			keyfile=$(head -1 "$i")
@@ -145,47 +152,40 @@ sign()
 		fi
 	done
 	[ "$KSS" != "" ] && KSS="$KEYDIR/$KSS"
-	$signzone "$_SIGN_PARAM" -o "$ZONE" -f "$ZONEFILE.signed" "$ZONEFILE.tmp" "$KEYDIR/$ZSK" "$KEYDIR/$KSK" "$KSS"
-	echo "signzone returns $?"
+	$SIGNZONE_CMD "$_SIGN_PARAM" -e "$EXPIRE" -o "$ZONE" -f "$ZONEFILE.signed" "$ZONEFILE.tmp" "$KEYDIR/$ZSK" "$KEYDIR/$KSK" $KSS || Fatal "Failed to sign zone" && $CHECKZONE_CMD $ZONE $ZONE
 	rm "$ZONEFILE.tmp"
-	eval "$RELOAD_COMMAND"
+	eval "$RELOAD_CMD"
 }
 
 status()
 {
-	DS_FILE_TMP="$DS_FILE.tmp"
-	if [ -f "$KSK_FILE" ]; then
-		printf "%s's KSK = " "$ZONE"
-		cat "$KSK_FILE";
-		$key2ds "$_DS_PARAM" "$KEYDIR/$(cat "$KSK_FILE").key" | tee "$DS_FILE_TMP"
+	_check_file "$KSK_CUR_FILE" "$ZSK_CUR_FILE"
+	echo $ZONE
+	echo " type state  id    algo hash (digest)"
+	$KEY2DS_CMD -n "$_DS_PARAM" "$KEYDIR/$(cat "$KSK_CUR_FILE").key" | \
+		awk {'printf (" KSK  active %5s %2s   %1s    %s\n", $5, $6, $7, $8)'}
+	if [ -f "$KSK_NEW_FILE" ]; then
+		$KEY2DS_CMD -n "$_DS_PARAM" "$KEYDIR/$(cat "$KSK_NEW_FILE").key" | \
+		  awk {'printf ("      next   %5s %3s  %1s %s\n", $5, $6, $7, $8)'}
 	fi
-	if [ -f "$KSK_S_FILE" ]; then
-		printf "%s's next KSK = " "$ZONE"
-		cat "$KSK_S_FILE";
-		$key2ds "$_DS_PARAM" "$KEYDIR/$(cat "$KSK_S_FILE").key" | tee -a "$DS_FILE_TMP"
+	awk {'split($0,a,"+"); gsub(/^0/, "", a[2]);
+	      printf (" ZSK  active %5s %2s   %1s\n", a[3], a[2], "'$DS_HASH'")'} "$ZSK_CUR_FILE"
+	if [ -f "$ZSK_NEW_FILE" ]; then
+		awk {'split($0,a,"+"); gsub(/^0/, "", a[2]);
+	              printf ("      next   %5s %2s   %1s\n", a[3], a[2], "'$DS_HASH'")'} "$ZSK_NEW_FILE"
 	fi
-	if [ -f "$ZSK_FILE" ]; then
-		printf "%s's ZSK = " "$ZONE"
-		cat "$ZSK_FILE";
+	if [ -f "$ZSK_OLD_FILE" ]; then
+		awk {'split($0,a,"+"); gsub(/^0/, "", a[2]);
+		      printf ("      old    %5s %2s   %1s\n", a[3], a[2], "'$DS_HASH'")'} "$ZSK_OLD_FILE"
 	fi
-	if [ -f "$ZSK_S_FILE" ]; then
-		printf "%s's next ZSK = " "$ZONE"
-		cat "$ZSK_S_FILE";
-	fi
-	if [ -f "$ZSK_R_FILE" ]; then
-		printf "%s's previous ZSK = " "$ZONE"
-		cat "$ZSK_R_FILE";
-	fi
-	mv -f "$DS_FILE_TMP" "$DS_FILE"
 }
 
-keygensub()
+keygen()
 {
 	cd "$KEYDIR" || Fatal "Can't change directory to \$KEYDIR"
-	echo "$keygen $1 $2"
 	newfile="$3"
 	tmpfile="$3.tmp"
-	_KEY=$($keygen "$1" "$2")
+	_KEY=$($KEYGEN_CMD $1 "$2") || Fatal "'$KEYGEN_CMD $1 \"$2\"' failed with $?"
 	[ -f "$_KEY.ds" ] && rm "$_KEY.ds"
 	if [ ! -s "$_KEY.key" ]; then
 		rm "$_KEY.key"
@@ -202,30 +202,27 @@ keygensub()
 	cd "$MASTERDIR" || Fatal "Can't change directory to \$MASTERDIR"
 }
 
-removekeys_sub()
+backupkeys()
 {
-	if [ -f "$1" ]; then
-		KEY=$(head -1 "$1")
-		if [ -f "$KEYDIR/$KEY.key" ]; then
-			mv "$KEYDIR/$KEY.key" "$KEYDIR/$KEY.private" "$KEYBACKUPDIR/"
+	while [ "$1" != "" ]; do
+		if [ -f "$1" ]; then
+			KEY=$(head -1 "$1")
+			if [ -f "$KEYDIR/$KEY.key" ]; then
+				mv "$KEYDIR/$KEY.key" "$KEYDIR/$KEY.private" "$KEYBACKUPDIR/"
+			fi
 		fi
-	fi
+		shift
+	done
 }
 
-remove_previouskey()
-{
-	if [ -f "$ZSK_R_FILE" ]; then
-		removekeys_sub "$ZSK_R_FILE"
-		mv "$ZSK_R_FILE" "$KEYBACKUPDIR/removed-ZSK-$NOW-$ZONE"
-	fi
-}
-
+# Process command line
 if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "-?" ] || [ "$1" = "--help" ]; then
 	_usage
-	exit 0
 elif [ "$1" = "-s" ] || [ "$1" = "--sign" ];then
 	SIGN_OPT=1
-	shift
+	if [ $# -gt 2 ]; then
+		shift
+	fi
 fi
 
 CMD="$1"
@@ -239,15 +236,13 @@ fi
 
 for ZONE in $ZONELIST
 do
-	LOCKF="$DBDIR/$ZONE.lock"
 	TMPF="$DBDIR/$ZONE.$$"
-	KSK_FILE="$KEYDIR/$HEAD_KSKNAME$ZONE"
-	ZSK_FILE="$KEYDIR/$HEAD_ZSKNAME$ZONE"
-	KSK_S_FILE="$KEYDIR/$HEAD_KSSNAME$ZONE"
-	ZSK_S_FILE="$KEYDIR/$HEAD_ZSSNAME$ZONE"
-	ZSK_R_FILE="$KEYDIR/$HEAD_ZSRNAME$ZONE"
+	KSK_CUR_FILE="$KEYDIR/$KSK_CUR_PREFIX$ZONE"
+	ZSK_CUR_FILE="$KEYDIR/$ZSK_CUR_PREFIX$ZONE"
+	KSK_NEW_FILE="$KEYDIR/$KSK_NEW_PREFIX$ZONE"
+	ZSK_NEW_FILE="$KEYDIR/$ZSK_NEW_PREFIX$ZONE"
+	ZSK_OLD_FILE="$KEYDIR/$ZSK_OLD_PREFIX$ZONE"
 	SERIAL_FILE="$SERIALDIR/$ZONE"
-	DS_FILE="$DSDIR/$ZONE"
 	ZONEFILE="$MASTERDIR/$ZONE"
 	ZONE_=$(echo "$ZONE" | tr .- __)
 	eval _SIGN_PARAM=\${SIGN_PARAM_"$ZONE_":-"$SIGN_PARAM"}
@@ -255,10 +250,15 @@ do
 	eval _ZSK_PARAM=\${ZSK_PARAM_"$ZONE_":-"$ZSK_PARAM"}
 	eval _DS_PARAM=\${DS_PARAM_"$ZONE_":-"$DS_PARAM"}
 
+	if [ ! -s "$KSK_CUR_FILE" ]; then
+		Fatal "Zone does not exist"
+	fi
+
+        LOCKF="$DBDIR/$ZONE.lock"
 	echo "LOCK$$" > "$TMPF"
 	LOCKSTR=$(cat "$TMPF")
 	if [ ! -f "$TMPF" ] || [ "LOCK$$" != "$LOCKSTR" ]; then
-		Fatal "cannot write lock file $TMPF"
+		Fatal "Cannot write lock file $TMPF"
 	fi
 	if ln "$TMPF" "$LOCKF"; then
 		:
@@ -268,78 +268,87 @@ do
 		continue
 	fi
 	rm "$TMPF"
+
 	case $CMD in
 	keygen)
-		_check_nofile "$KSK_FILE" "$ZSK_FILE"
-		keygensub "$_KSK_PARAM" "$ZONE" "$KSK_FILE"
-		keygensub "$_ZSK_PARAM" "$ZONE" "$ZSK_FILE"
+		_check_nofile "$KSK_CUR_FILE" "$ZSK_CUR_FILE"
+		keygen "$_KSK_PARAM" "$ZONE" "$KSK_CUR_FILE"
+		keygen "$_ZSK_PARAM" "$ZONE" "$ZSK_CUR_FILE"
+		echo "New keys created"
 		status
 		;;
 	rmkeys)
-		removekeys_sub "$KSK_FILE"
-		removekeys_sub "$ZSK_FILE"
-		removekeys_sub "$KSK_S_FILE"
-		removekeys_sub "$ZSK_S_FILE"
-		rm "$KSK_FILE" "$ZSK_FILE" "$KSK_S_FILE" "$ZSK_S_FILE"
+
+		backupkeys "$KSK_CUR_FILE" "$ZSK_CUR_FILE" "$KSK_NEW_FILE" "$ZSK_NEW_FILE"
+		rm "$KSK_CUR_FILE" "$ZSK_CUR_FILE" "$KSK_NEW_FILE" "$ZSK_NEW_FILE"
+		echo "Removed all keys"
 		status
 		;;
 	ksk-add)
-		_check_nofile "$KSK_S_FILE"
-		keygensub "$_KSK_PARAM" "$ZONE" "$KSK_S_FILE"
+		_check_nofile "$KSK_NEW_FILE"
+		keygen "$_KSK_PARAM" "$ZONE" "$KSK_NEW_FILE"
+		echo "Added new KSK"
 		status
 		;;
 	ksk-roll)
-		_check_file "$ZONEFILE" "$KSK_FILE" "$KSK_S_FILE"
-		KSK=$(head -1 "$KSK_FILE")
-		KSS=$(head -1 "$KSK_S_FILE")
+		_check_file "$ZONEFILE" "$KSK_CUR_FILE" "$KSK_NEW_FILE"
+		KSK=$(head -1 "$KSK_CUR_FILE")
+		KSS=$(head -1 "$KSK_NEW_FILE")
 		_check_file "$KEYDIR/$KSK.key" "$KEYDIR/$KSS.key" "$KEYDIR/$KSK.private" "$KEYDIR/$KSS.private"
 		mv "$KEYDIR/$KSK.key" "$KEYDIR/$KSK.private" "$KEYBACKUPDIR/"
-		mv "$KSK_S_FILE" "$KSK_FILE"
+		mv "$KSK_NEW_FILE" "$KSK_CUR_FILE"
 		OLDKSK="$KSK"
 		KSK="$KSS"
 		KSS=""
-		echo "$ZONE 's KSK: valid -> removed: $OLDKSK"
-		echo "$ZONE 's KSK: next  -> current: $KSK"
+		echo "Removed old KSK"
 		status
 		;;
 	zsk-add)
-		_check_nofile "$ZSK_S_FILE"
-		keygensub "$_ZSK_PARAM" "$ZONE" "$ZSK_S_FILE"
+		_check_nofile "$ZSK_NEW_FILE"
+		keygen "$_ZSK_PARAM" "$ZONE" "$ZSK_NEW_FILE"
+		echo "New ZSK created"
 		status
 		;;
 	zsk-roll)
-		_check_file "$ZONEFILE" "$ZSK_FILE" "$ZSK_S_FILE"
-		ZSK=$(head -1 "$ZSK_FILE")
-		ZSS=$(head -1 "$ZSK_S_FILE")
+		_check_file "$ZONEFILE" "$ZSK_CUR_FILE" "$ZSK_NEW_FILE"
+		ZSK=$(head -1 "$ZSK_CUR_FILE")
+		ZSS=$(head -1 "$ZSK_NEW_FILE")
 		_check_file "$KEYDIR/$ZSK.key" "$KEYDIR/$ZSS.key" "$KEYDIR/$ZSK.private" "$KEYDIR/$ZSS.private"
-		remove_previouskey
-		mv "$ZSK_FILE" "$ZSK_R_FILE"
-		mv "$ZSK_S_FILE" "$ZSK_FILE"
+		backupkeys "$ZSK_OLD_FILE"
+		mv "$ZSK_OLD_FILE" "$KEYBACKUPDIR/removed-ZSK-$NOW-$ZONE"
+		mv "$ZSK_CUR_FILE" "$ZSK_OLD_FILE"
+		mv "$ZSK_NEW_FILE" "$ZSK_CUR_FILE"
 		OLDZSK="$ZSK"
 		ZSK="$ZSS"
 		ZSS=""
-		echo "$ZONE 's ZSK: valid -> previous: $OLDZSK"
-		echo "$ZONE 's ZSK: next -> current: $ZSK"
+		echo "Rolled ZSK - active set to old & new set to active"
 		status
 		;;
 	zsk-rmold)
-		_check_file "$ZSK_R_FILE"
-		remove_previouskey
+		_check_file "$ZSK_OLD_FILE"
+		backupkeys "$ZSK_OLD_FILE"
+		mv "$ZSK_OLD_FILE" "$KEYBACKUPDIR/removed-ZSK-$NOW-$ZONE"
+		echo "Removed old ZSK"
 		status
-		;;
-	sign)
-		sign
 		;;
 	status)
 		status
+		;;
+	sign|-s|--sign)
+		sign
+		SIGN_OPT=0
 		;;
 	*)
 		echo "unknown command: $CMD"
 		_usage
 		;;
 	esac
+
+	if [ "$SIGN_OPT" = 1 ]; then
+		sleep 5
+		sign
+	fi
 	rm "$LOCKF"
 done
 
-[ "$SIGN_OPT" = 1 ] && sign
 exit 0
