Multiple fixes and adaptation | conf update required
- Added a $DNS_TOOL variable to identify nsd vs bind usage
- Identification of *BSD vs Linux to adapt commands
- ED25519 instead of ECDSAP256SHA265
- Remove NSEC3
- 36 days expiration instead of 33
- Fix #24 and #23
- Should address #18 and #25 - TBC or adapted by bind users

diff --git a/dnssec-reverb b/dnssec-reverb
--- a/dnssec-reverb
+++ b/dnssec-reverb
@@ -1,5 +1,6 @@
 #!/bin/sh
 # dnssec-reverb: DNSSEC key management tool
+# Tested on OpenBSD with NSD dnssec toolset
 #
 # @home: https://github.com/northox/dnssec-reverb
 # @license: Simplified BSD
@@ -15,12 +16,12 @@ KEY2DS_CMD="$(which ldns-key2ds)"
 CHECKZONE_CMD="$(which nsd-checkzone)"
 CONTROL_CMD="$(which nsd-control)"
 RELOAD_CMD="(echo -n 'reload is '; $CONTROL_CMD reload) && (echo -n 'notify is '; $CONTROL_CMD notify)"
-KSK_PARAM="-a ECDSAP256SHA256 -k"
-ZSK_PARAM="-a ECDSAP256SHA256"
-SIGN_PARAM="-n" # -n = use NSEC3
+KSK_PARAM="-a ED25519 -k"
+ZSK_PARAM="-a ED25519"
+SIGN_PARAM="" # -n -a 1 -t 0
 DS_HASH="2" # 1=SHA1 2=SHA256 3=GOST 4=SHA384
 DS_PARAM="-$DS_HASH"
-EXPIRE_DAYS="33"
+EXPIRE_DAYS="36"
 SERIAL_TAG="00001111"
 
 NOW=$(date +%Y%m%d%H%M%S)
@@ -55,11 +56,12 @@ fi
 . "$CONF"
 
 # defaults
-[ "$KEYGEN_CMD" = "" ] && Fatal "cannot find \$KEYGEN_CMD ($KEYGEN_CMD)"
-[ "$SIGNZONE_CMD" = "" ] && Fatal "cannot find \$SIGNZONE_CMD ($SIGNZONE_CMD)"
-[ "$KEY2DS_CMD" = "" ] && Fatal "cannot find \$KEY2DS_CMD ($KEY2DS_CMD)"
-[ "$CHECKZONE_CMD" = "" ] && Fatal "cannot find \$CHECKZONE_CMD ($CHECKZONE_CMD)"
-[ "$CONTROL_CMD" = "" ] && Fatal "cannot find \$CONTROL_CMD ($CONTROL_CMD)"
+DNS_TOOL=${DNS_TOOL:-nsd}
+[ "$KEYGEN_CMD" = "" ] && Fatal "cannot find \$KEYZONE_CMD"
+[ "$SIGNZONE_CMD" = "" ] && Fatal "cannot find \$SIGNZONE_CMD"
+[ "$KEY2DS_CMD" = "" ] && Fatal "cannot find \$KEY2DS_CMD"
+[ "$CHECKZONE_CMD" = "" ] && Fatal "cannot find \$CHECKZONE_CMD"
+[ "$CONTROL_CMD" = "" ] && Fatal "cannot find \$CONTROL_CMD"
 [ "$MASTERDIR" = "" ] && Fatal "\$MASTERDIR not set"
 [ -d "$MASTERDIR" ] || Fatal "\$MASTERDIR not a directory ($MASTERDIR)"
 [ "$DBDIR" = "" ] && DBDIR="$MASTERDIR/dnssec-reverb-db"
@@ -72,6 +74,16 @@ KSK_CUR_PREFIX="ksk-" # current ksk
 ZSK_NEW_PREFIX="zss-" # new zsk
 KSK_NEW_PREFIX="kss-" # new ksk
 ZSK_OLD_PREFIX="zsr-" # removed zsk
+
+_OS=$(uname)
+if [ "$_OS" = "Linux" ]; then
+    OS_TYPE="Linux"
+elif echo "$_OS" | grep -q "BSD"; then
+    OS_TYPE="BSD"
+else
+    echo "Unsupported operating system: $_OS"
+    exit 1
+fi
 
 # setup
 [ ! -d "$DBDIR" ] && mkdir -p "$DBDIR"
@@ -154,13 +166,18 @@ sign()
 	[ "$KSS" != "" ] && KSS="$KEYDIR/$KSS"
 	
 	EXPIRE_ABS=$(echo "`date +%s` + (${EXPIRE_DAYS}*24*60*60)" | bc)
-	if [[ $signzone = *'dnssec-signzone' ]]; then # if bind
+	if [ $DNS_TOOL = 'bind' ]; then
 		EXPIRE=$(echo "+`echo "(${EXPIRE_DAYS}*24*60*60)" | bc`")
 	else
 		EXPIRE=$EXPIRE_ABS
 	fi
-	$SIGNZONE_CMD "$_SIGN_PARAM" -e "$EXP" -o "$ZONE" -f "$ZONEFILE.signed" "$ZONEFILE.tmp" "$KEYDIR/$ZSK" "$KEYDIR/$KSK" $KSS || Fatal "failed to sign zone" && $CHECKZONE_CMD $ZONE $ZONE
-	TT=$EXPIRE; date -r "$TT" '+%Y/%m/%d %H:%M:%S' > "$KEYDIR/$ZSK.expire"
+	$SIGNZONE_CMD $_SIGN_PARAM -e "$EXP" -o "$ZONE" -f "$ZONEFILE.signed" "$ZONEFILE.tmp" "$KEYDIR/$ZSK" "$KEYDIR/$KSK" $KSS || Fatal "failed to sign zone" && $CHECKZONE_CMD $ZONE $ZONE
+	TT=$EXPIRE
+	if [ "$OS_TYPE" = "Linux" ]; then
+		date -d "@$TT" '+%Y/%m/%d %H:%M:%S' > "$KEYDIR/$ZSK.expire"
+	elif [ "$OS_TYPE" = "BSD" ]; then
+		TT=$EXPIRE; date -r "$TT" '+%Y/%m/%d %H:%M:%S' > "$KEYDIR/$ZSK.expire"
+	fi
 	rm "$ZONEFILE.tmp"
 	eval "$RELOAD_CMD"
 }
@@ -335,7 +352,6 @@ do
 		ZSS=$(head -1 "$ZSK_NEW_FILE")
 		_check_file "$KEYDIR/$ZSK.key" "$KEYDIR/$ZSS.key" "$KEYDIR/$ZSK.private" "$KEYDIR/$ZSS.private"
 		backupkeys "$ZSK_OLD_FILE"
-		mv "$ZSK_OLD_FILE" "$KEYBACKUPDIR/removed-ZSK-$NOW-$ZONE"
 		mv "$ZSK_CUR_FILE" "$ZSK_OLD_FILE"
 		mv "$ZSK_NEW_FILE" "$ZSK_CUR_FILE"
 		OLDZSK="$ZSK"
